### ISSUE TITLE
Inquiry about the HR image‘s resolution and their processing method

### ISSUE THREAD

**Issue by wangjiyuan9** [svip-lab/PlaneDepth#6]
Dear authors,

I am currently following your fantastic work and have noticed that in your paper, you mentioned fine-tuning the network on high-resolution images of 1280*384. However, in the KITTI dataset, the maximum resolution shown in image_02 is 1242*375. Therefore, I would like to inquire whether the high-resolution images were cropped or resized to achieve the resolution of 1280*384. If cropping was used, could you please provide more information on how the cropping was performed? If resizing was used, could you please clarify the method used for resizing? Thank you for your time and consideration.

Sincerely!

**Comment by Dwawayu** [comment]
Hi Jiyuan! Thank you for your interest and kind words. We do not crop the images and only resize them to `1280X384` during the finetune stage to utilize the vertical image position cue. The process code is [here](https://github.com/svip-lab/PlaneDepth/blob/c38334aab55be50f6b97b0d225cb7dadd58a29fb/datasets/pair_transforms.py#LL58C9-L58C9), which resizes the images using `mode="bicubic"`.

You also pointed out that the image resolution of KITTI is just `1242X375`. We upsample the images because we follow the FalNet's evaluation resolution in `1280X384`, and the resolution during finetune has to be consistent with that during evaluation.

I hope this answers your question. Please feel free to contact me if you have any further issues.

**Comment by wangjiyuan9** [comment]
Thanks! WaWaYu!
Here is a Further question：
Can I assume that image resizing has little effect on depth estimation? For example, if I resize an image to 1216x352, add data augmentation, and then perform depth estimation, the difference in results between this approach and directly performing augment should not be significant, right?

**Comment by wangjiyuan9** [comment]
A very insightful understanding, thank you for your response, it was very helpful!
